-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 12:34:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `discount` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car` (
  `idCar` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NOT NULL,
  `vin` VARCHAR(45) NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `bodyType` VARCHAR(45) NOT NULL,
  `productionYear` INT NOT NULL,
  `engineCapacity` VARCHAR(45) NOT NULL,
  `fuelType` VARCHAR(45) NOT NULL,
  `exteriorColor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCar`),
  UNIQUE INDEX `Vin_UNIQUE` (`vin` ASC) VISIBLE,
  INDEX `fk_Car_Customer1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Car_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CarServiceA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CarServiceA` (
  `idCarServiceA` INT NOT NULL AUTO_INCREMENT,
  `idCar` INT NULL,
  `serviceType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarServiceA`),
  INDEX `fk_Car Service A_Car1_idx` (`idCar` ASC) VISIBLE,
  CONSTRAINT `fk_Car Service A_Car1`
    FOREIGN KEY (`idCar`)
    REFERENCES `mydb`.`Car` (`idCar`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idManager` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`idManager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `idManager` INT NOT NULL,
  PRIMARY KEY (`idEmployees`),
  INDEX `fk_Employees_Manager1_idx` (`idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Manager1`
    FOREIGN KEY (`idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EngineMechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EngineMechanic` (
  `idEngineMechanic` INT NOT NULL AUTO_INCREMENT,
  `idCarServiceA` INT NULL,
  `idEmployees` INT NULL,
  PRIMARY KEY (`idEngineMechanic`),
  INDEX `fk_Engine Mechanic_Car Service A1_idx` (`idCarServiceA` ASC) VISIBLE,
  INDEX `fk_Engine Mechanic_Employees1_idx` (`idEmployees` ASC) VISIBLE,
  CONSTRAINT `fk_Engine Mechanic_Car Service A1`
    FOREIGN KEY (`idCarServiceA`)
    REFERENCES `mydb`.`CarServiceA` (`idCarServiceA`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Engine Mechanic_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CarServiceB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CarServiceB` (
  `idCarServiceB` INT NOT NULL AUTO_INCREMENT,
  `idCar` INT NULL,
  `serviceType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarServiceB`),
  INDEX `fk_Car Service B_Car1_idx` (`idCar` ASC) VISIBLE,
  CONSTRAINT `fk_Car Service B_Car1`
    FOREIGN KEY (`idCar`)
    REFERENCES `mydb`.`Car` (`idCar`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiagnosticsMechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DiagnosticsMechanic` (
  `idDiagnosticsMechanic` INT NOT NULL,
  `idCarServiceA` INT NULL,
  `idEmployees` INT NULL,
  INDEX `fk_Diagnostics Mechanic_Car Service A1_idx` (`idCarServiceA` ASC) VISIBLE,
  INDEX `fk_Diagnostics Mechanic_Employees1_idx` (`idEmployees` ASC) VISIBLE,
  PRIMARY KEY (`idDiagnosticsMechanic`),
  CONSTRAINT `fk_Diagnostics Mechanic_Car Service A1`
    FOREIGN KEY (`idCarServiceA`)
    REFERENCES `mydb`.`CarServiceA` (`idCarServiceA`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Diagnostics Mechanic_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AutomotiveElectrician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AutomotiveElectrician` (
  `idAutomotiveElectrician` INT NOT NULL,
  `idCarServiceB` INT NULL,
  `idEmployees` INT NULL,
  INDEX `fk_Automotive Electrician_Car Service B1_idx` (`idCarServiceB` ASC) VISIBLE,
  INDEX `fk_Automotive Electrician_Employees1_idx` (`idEmployees` ASC) VISIBLE,
  PRIMARY KEY (`idAutomotiveElectrician`),
  CONSTRAINT `fk_Automotive Electrician_Car Service B1`
    FOREIGN KEY (`idCarServiceB`)
    REFERENCES `mydb`.`CarServiceB` (`idCarServiceB`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Automotive Electrician_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SuspensionMechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SuspensionMechanic` (
  `idSuspensionMechanic` INT NOT NULL,
  `idCarServiceB` INT NULL,
  `idEmployees` INT NULL,
  INDEX `fk_Suspension Mechanic_Car Service B1_idx` (`idCarServiceB` ASC) VISIBLE,
  INDEX `fk_Suspension Mechanic_Employees1_idx` (`idEmployees` ASC) VISIBLE,
  PRIMARY KEY (`idSuspensionMechanic`),
  CONSTRAINT `fk_Suspension Mechanic_Car Service B1`
    FOREIGN KEY (`idCarServiceB`)
    REFERENCES `mydb`.`CarServiceB` (`idCarServiceB`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Suspension Mechanic_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GearboxMechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GearboxMechanic` (
  `idGearboxMechanic` INT NOT NULL,
  `idCarServiceB` INT NULL,
  `idEmployees` INT NULL,
  INDEX `fk_Gearbox Mechanic_Car Service B1_idx` (`idCarServiceB` ASC) VISIBLE,
  INDEX `fk_Gearbox Mechanic_Employees1_idx` (`idEmployees` ASC) VISIBLE,
  PRIMARY KEY (`idGearboxMechanic`),
  CONSTRAINT `fk_Gearbox Mechanic_Car Service B1`
    FOREIGN KEY (`idCarServiceB`)
    REFERENCES `mydb`.`CarServiceB` (`idCarServiceB`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Gearbox Mechanic_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сashier` (
  `idСashier` INT NOT NULL AUTO_INCREMENT,
  `idEmployees` INT NULL,
  PRIMARY KEY (`idСashier`),
  INDEX `fk_Сashier_Employees1_idx` (`idEmployees` ASC) VISIBLE,
  CONSTRAINT `fk_Сashier_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PartWarehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PartWarehouse` (
  `idPartWarehouse` INT NOT NULL,
  `partid` VARCHAR(45) NOT NULL,
  `partName` VARCHAR(45) NOT NULL,
  `partNumber` VARCHAR(45) NOT NULL,
  `partQuantity` INT NOT NULL,
  `producer` VARCHAR(45) NOT NULL,
  `releaseYear` INT NOT NULL,
  PRIMARY KEY (`idPartWarehouse`, `partid`),
  UNIQUE INDEX `part id_UNIQUE` (`partid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EnginePartsStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EnginePartsStore` (
  `idEnginePartsStore` INT NOT NULL AUTO_INCREMENT,
  `idСashier` INT NOT NULL,
  `idPartWarehouse` INT NOT NULL,
  `partid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEnginePartsStore`),
  INDEX `fk_Engine Parts Store_Сashier1_idx` (`idСashier` ASC) VISIBLE,
  INDEX `fk_Engine Parts Store_Part Warehouse1_idx` (`idPartWarehouse` ASC, `partid` ASC) VISIBLE,
  CONSTRAINT `fk_Engine Parts Store_Сashier1`
    FOREIGN KEY (`idСashier`)
    REFERENCES `mydb`.`Сashier` (`idСashier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Engine Parts Store_Part Warehouse1`
    FOREIGN KEY (`idPartWarehouse` , `partid`)
    REFERENCES `mydb`.`PartWarehouse` (`idPartWarehouse` , `partid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AutomotivePartsStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AutomotivePartsStore` (
  `idAutomotivePartsStore` INT NOT NULL AUTO_INCREMENT,
  `idCashier` INT NOT NULL,
  `idPartWarehouse` INT NOT NULL,
  `partid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutomotivePartsStore`),
  INDEX `fk_Automotive Parts Store_Part Warehouse1_idx` (`idPartWarehouse` ASC, `partid` ASC) VISIBLE,
  INDEX `fk_AutomotivePartsStore_Сashier1_idx` (`idCashier` ASC) VISIBLE,
  CONSTRAINT `fk_Automotive Parts Store_Part Warehouse1`
    FOREIGN KEY (`idPartWarehouse` , `partid`)
    REFERENCES `mydb`.`PartWarehouse` (`idPartWarehouse` , `partid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AutomotivePartsStore_Сashier1`
    FOREIGN KEY (`idCashier`)
    REFERENCES `mydb`.`Сashier` (`idСashier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EnginePartsStoreOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EnginePartsStoreOrders` (
  `idCustomer` INT NOT NULL,
  `idEnginePartsStore` INT NOT NULL,
  `idOrder` VARCHAR(45) NOT NULL,
  `orderDate` DATE NOT NULL,
  `orderAmount` DOUBLE NOT NULL,
  PRIMARY KEY (`idCustomer`, `idEnginePartsStore`, `idOrder`),
  INDEX `fk_Customer_has_EnginePartsStore_EnginePartsStore1_idx` (`idEnginePartsStore` ASC) VISIBLE,
  INDEX `fk_Customer_has_EnginePartsStore_Customer1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_EnginePartsStore_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_EnginePartsStore_EnginePartsStore1`
    FOREIGN KEY (`idEnginePartsStore`)
    REFERENCES `mydb`.`EnginePartsStore` (`idEnginePartsStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AutomotivePartsStoreOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AutomotivePartsStoreOrders` (
  `idCustomer` INT NOT NULL,
  `idAutomotivePartsStore` INT NOT NULL,
  `idOrder` VARCHAR(45) NOT NULL,
  `orderDate` DATE NOT NULL,
  `orderAmount` DOUBLE NOT NULL,
  PRIMARY KEY (`idCustomer`, `idAutomotivePartsStore`, `idOrder`),
  INDEX `fk_Customer_has_AutomotivePartsStore_AutomotivePartsStore1_idx` (`idAutomotivePartsStore` ASC) VISIBLE,
  INDEX `fk_Customer_has_AutomotivePartsStore_Customer1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_AutomotivePartsStore_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_AutomotivePartsStore_AutomotivePartsStore1`
    FOREIGN KEY (`idAutomotivePartsStore`)
    REFERENCES `mydb`.`AutomotivePartsStore` (`idAutomotivePartsStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
