-- MySQL Script generated by MySQL Workbench
-- Sun Jan  8 15:55:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `discount` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car` (
  `idCar` INT NOT NULL AUTO_INCREMENT,
  `CustomerID(owner)` INT NOT NULL,
  `vin` VARCHAR(45) NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `bodytype` VARCHAR(45) NOT NULL,
  `productionyear` INT NOT NULL,
  `enginecapacity` VARCHAR(45) NOT NULL,
  `fueltype` VARCHAR(45) NOT NULL,
  `exteriorcolor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCar`),
  UNIQUE INDEX `Vin_UNIQUE` (`vin` ASC) VISIBLE,
  INDEX `fk_Car_Customer1_idx` (`CustomerID(owner)` ASC) VISIBLE,
  CONSTRAINT `fk_Car_Customer1`
    FOREIGN KEY (`CustomerID(owner)`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car Service A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car Service A` (
  `idCar Service A` INT NOT NULL AUTO_INCREMENT,
  `sname` VARCHAR(45) NOT NULL,
  `sadress` VARCHAR(45) NOT NULL,
  `serviceTypes` VARCHAR(45) NOT NULL,
  `Car_idCar` INT NOT NULL,
  PRIMARY KEY (`idCar Service A`),
  INDEX `fk_Car Service A_Car1_idx` (`Car_idCar` ASC) VISIBLE,
  CONSTRAINT `fk_Car Service A_Car1`
    FOREIGN KEY (`Car_idCar`)
    REFERENCES `mydb`.`Car` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idManager` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phonenumber` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`idManager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `ManagerID` INT NOT NULL,
  PRIMARY KEY (`idEmployees`),
  INDEX `fk_Employees_Manager1_idx` (`ManagerID` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Manager1`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Engine Mechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Engine Mechanic` (
  `idMechanic` INT NOT NULL AUTO_INCREMENT,
  `idCar Service A` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  PRIMARY KEY (`idMechanic`),
  INDEX `fk_Engine Mechanic_Car Service A1_idx` (`idCar Service A` ASC) VISIBLE,
  INDEX `fk_Engine Mechanic_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Engine Mechanic_Car Service A1`
    FOREIGN KEY (`idCar Service A`)
    REFERENCES `mydb`.`Car Service A` (`idCar Service A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Engine Mechanic_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car Service B`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car Service B` (
  `idCar Service B` INT NOT NULL,
  `sname` VARCHAR(45) NOT NULL,
  `sadress` VARCHAR(45) NOT NULL,
  `serviceTypes` VARCHAR(45) NOT NULL,
  `Car_idCar` INT NOT NULL,
  PRIMARY KEY (`idCar Service B`),
  INDEX `fk_Car Service B_Car1_idx` (`Car_idCar` ASC) VISIBLE,
  CONSTRAINT `fk_Car Service B_Car1`
    FOREIGN KEY (`Car_idCar`)
    REFERENCES `mydb`.`Car` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnostics Mechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnostics Mechanic` (
  `idCar Service A` INT NOT NULL AUTO_INCREMENT,
  `EmployeeID` INT NOT NULL,
  INDEX `fk_Diagnostics Mechanic_Car Service A1_idx` (`idCar Service A` ASC) VISIBLE,
  INDEX `fk_Diagnostics Mechanic_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnostics Mechanic_Car Service A1`
    FOREIGN KEY (`idCar Service A`)
    REFERENCES `mydb`.`Car Service A` (`idCar Service A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnostics Mechanic_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Automotive Electrician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Automotive Electrician` (
  `idCar Service B` INT NOT NULL AUTO_INCREMENT,
  `EmployeeID` INT NOT NULL,
  INDEX `fk_Automotive Electrician_Car Service B1_idx` (`idCar Service B` ASC) VISIBLE,
  INDEX `fk_Automotive Electrician_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Automotive Electrician_Car Service B1`
    FOREIGN KEY (`idCar Service B`)
    REFERENCES `mydb`.`Car Service B` (`idCar Service B`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Automotive Electrician_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Suspension Mechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suspension Mechanic` (
  `idCar Service B` INT NOT NULL AUTO_INCREMENT,
  `EmployeeID` INT NOT NULL,
  INDEX `fk_Suspension Mechanic_Car Service B1_idx` (`idCar Service B` ASC) VISIBLE,
  INDEX `fk_Suspension Mechanic_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Suspension Mechanic_Car Service B1`
    FOREIGN KEY (`idCar Service B`)
    REFERENCES `mydb`.`Car Service B` (`idCar Service B`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suspension Mechanic_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gearbox Mechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gearbox Mechanic` (
  `idCar Service B` INT NOT NULL AUTO_INCREMENT,
  `EmployeeID` INT NOT NULL,
  INDEX `fk_Gearbox Mechanic_Car Service B1_idx` (`idCar Service B` ASC) VISIBLE,
  INDEX `fk_Gearbox Mechanic_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Gearbox Mechanic_Car Service B1`
    FOREIGN KEY (`idCar Service B`)
    REFERENCES `mydb`.`Car Service B` (`idCar Service B`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gearbox Mechanic_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сashier` (
  `idСashier` INT NOT NULL AUTO_INCREMENT,
  `EmployeeID` INT NOT NULL,
  PRIMARY KEY (`idСashier`),
  INDEX `fk_Сashier_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Сashier_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `idOrders` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `orderedProducts` VARCHAR(45) NOT NULL,
  `orderAmount` DOUBLE NOT NULL,
  `orderDate` DATE NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Customer1_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Part Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Part Warehouse` (
  `idPart Warehouse` INT NOT NULL,
  `partname` VARCHAR(45) NOT NULL,
  `partnumber` VARCHAR(45) NOT NULL,
  `partquantity` VARCHAR(45) NOT NULL,
  `producer` VARCHAR(45) NOT NULL,
  `releaseyear` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPart Warehouse`, `partname`, `partnumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Engine Parts Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Engine Parts Store` (
  `idEngine Parts Store` INT NOT NULL,
  `Сashier_idСashier` INT NOT NULL,
  `Orders_idOrders` INT NOT NULL,
  `Part Warehouse_idPart Warehouse` INT NOT NULL,
  `Part Warehouse_partnumber` VARCHAR(45) NOT NULL,
  `Part Warehouse_partname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEngine Parts Store`),
  INDEX `fk_Engine Parts Store_Сashier1_idx` (`Сashier_idСashier` ASC) VISIBLE,
  INDEX `fk_Engine Parts Store_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  INDEX `fk_Engine Parts Store_Part Warehouse1_idx` (`Part Warehouse_idPart Warehouse` ASC, `Part Warehouse_partnumber` ASC, `Part Warehouse_partname` ASC) VISIBLE,
  CONSTRAINT `fk_Engine Parts Store_Сashier1`
    FOREIGN KEY (`Сashier_idСashier`)
    REFERENCES `mydb`.`Сashier` (`idСashier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Engine Parts Store_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `mydb`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Engine Parts Store_Part Warehouse1`
    FOREIGN KEY (`Part Warehouse_idPart Warehouse` , `Part Warehouse_partnumber` , `Part Warehouse_partname`)
    REFERENCES `mydb`.`Part Warehouse` (`idPart Warehouse` , `partnumber` , `partname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Automotive Parts Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Automotive Parts Store` (
  `idAutomotive Parts Store` INT NOT NULL,
  `Сashier_idСashier` INT NOT NULL,
  `Orders_idOrders` INT NOT NULL,
  `PartWarehouseID` INT NOT NULL,
  `Part Warehouse_partnumber` VARCHAR(45) NOT NULL,
  `Part Warehouse_partname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutomotive Parts Store`),
  INDEX `fk_Automotive Parts Store_Сashier1_idx` (`Сashier_idСashier` ASC) VISIBLE,
  INDEX `fk_Automotive Parts Store_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  INDEX `fk_Automotive Parts Store_Part Warehouse1_idx` (`PartWarehouseID` ASC, `Part Warehouse_partnumber` ASC, `Part Warehouse_partname` ASC) VISIBLE,
  CONSTRAINT `fk_Automotive Parts Store_Сashier1`
    FOREIGN KEY (`Сashier_idСashier`)
    REFERENCES `mydb`.`Сashier` (`idСashier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Automotive Parts Store_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `mydb`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Automotive Parts Store_Part Warehouse1`
    FOREIGN KEY (`PartWarehouseID` , `Part Warehouse_partnumber` , `Part Warehouse_partname`)
    REFERENCES `mydb`.`Part Warehouse` (`idPart Warehouse` , `partnumber` , `partname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
